    name: {CI workflow}
    on: {
      push: {
        branches: ["main"]
      }
      pull_request: {
        branches: ["main"]
      }
    }
    jobs:
      build:
        runs-on: ubuntu-latest
          container: python:3.9-slim
steps:
- name: Upload code coverage
- uses: codecov/codecov-action@v2
  with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./coverage1.xml
        flags: unittests
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
        version: "v0.1.13"